### ISSUE TITLE
support subjectAltName verification for myproxy-server certificate

### ISSUE THREAD

**Issue by jbasney** [ncsa/security-lib#2]
[MyTrustManager.checkServerDN](https://github.com/ncsa/security-lib/blob/master/ncsa-security-common/ncsa-security-util/src/main/java/edu/uiuc/ncsa/security/util/ssl/MyTrustManager.java#L231) requires the myproxy-server hostname to appear in the certificate subject CN. However, Globus services like MyProxy are expected to support full [RFC 2818 verification](https://docs.globus.org/security-bulletins/2015-12-strict-mode/), including subjectAltName checking.

Ideally we could do away with MyTrustManager and use built-in Java TLS RFC 2818 verification, but we currently need MyTrustManager for custom DN matching (MyTrustManager.setServerDN) and custom trust roots (MyTrustManager.setTrustRootPath), which I think forces us to implement our own X509TrustManager.checkServerTrusted. So probably this means we need to implement our own subjectAltName checking in MyTrustManager.

JGlobus has a similar [issue](https://github.com/jglobus/JGlobus/issues/159).

**Comment by jjg-123** [comment]
This was needed for CILogon which no longer supports MyProxy. Therefore this will not be done.

**Comment by jjg-123** [comment]
Won't do.

**Comment by jjg-123** [comment]
won't do
